.stylelintrc.js, package.json, src/App.vue, src/components/LanguageSelect.vue, src/components/MapAside.vue, src/components/SearchLine.vue, src/components/SiteLogo.vue, src/styles/base.css, src/views/Home.vue, src/views/Map.vue, yarn.lock
- сортирует правила в нужном порядке
- Линтит файлы при коммите
=> Stylelint setup

package.json, src/assets/sprite-icons/arrow-right.svg, src/assets/sprite.svg, src/components/MapAside.vue, src/main.ts, src/styles/base.css, src/views/Home.vue, yarn.lock
=> setup svg sprites

src/api/search/index.ts, src/api/search/queries.ts, src/components/MapAside.vue, src/components/MapMarker.vue, src/components/MapPopup.vue, src/components/RelationInfo.vue, src/components/RelationsList.vue, src/router/index.ts, src/store/modules/app/actionTypes.ts, src/store/modules/app/index.ts, src/types/relation.ts, src/views/Home.vue, src/views/Map.vue
=> Refactor search 

src/components/MapAside.vue, src/router/index.ts, src/views/Home.vue
=> Refactor routes

src/api/search/queries.ts, src/components/LocationCard.vue, src/components/MapPopup.vue, src/components/RelationInfo.vue, src/types/address.ts, src/types/location.ts
=> Show location address

src/api/search/queries.ts, src/components/MapPopup.vue, src/components/RelationInfo.vue, src/types/location.ts, src/types/locationType.ts
=> Show location types

src/components/MapAside.vue
=> Fix navigation duplicate error

src/api/search/queries.ts, src/components/LocationCard.vue, src/styles/custom-properties.css, src/types/location.ts, src/types/person.ts, src/types/relation.ts
=> Show persons in location card

src/api/search/index.ts, src/api/search/queries.ts, src/components/LocationCard.vue, src/components/PersonCard.vue, src/router/index.ts, src/types/person.ts
=> Link to person card

.github/.env.gpg, .github/scripts/decrypt_secret.sh, .github/workflows/main.yml, src/assets/sprite-icons/arrow-left.svg, src/assets/sprite.svg, src/components/Aside.vue, src/styles/variables.css, src/views/Map.vue
=> [Refactor] Implement new aside

src/components/Aside.vue, src/components/LanguageSelect.vue, src/components/SiteLogo.vue, src/styles/custom-properties.css, src/styles/variables.css
Adds site logo and language selector to aside header.
=> [Feature] Aside header

src/assets/sprite-icons/checkbox-checked.svg, src/assets/sprite-icons/checkbox.svg, src/assets/sprite-icons/cross.svg, src/assets/sprite.svg, src/components/Aside.vue, src/components/CustomSelect.vue, src/styles/variables.css
=> [Feature] Add custom select

src/components/Aside.vue, src/components/CustomSelect.vue
=> [Feature] Add search button

.env, README.md, package.json, src/components/MapView.tsx, src/index.tsx, yarn.lock
Adds mapbox-gl library, implements MapView component.
=> [Feature] Implement mapbox

.env, package.json, src/index.tsx, yarn.lock
Connects application to Sentry tracker.
=> [Feature] Connect sentry

package.json, src/App.tsx, src/components/LeftPanel.tsx, src/pages/HomePage.tsx, src/reportWebVitals.ts, src/styles/ColorVariables.ts, src/styles/GlobalStyles.ts, src/styles/ShadowVariables.ts
Adds left panel component as a wrapper for asides in future.
=> [Feature] Left panel component

.github/workflows/main.yml, Dockerfile, nginx.conf, package.json, src/components/MapView.tsx, src/index.tsx, yarn.lock
Adds deployment workflow and Dockerfile.
=> [Feature] Add deploy workflow

package.json, public/index.html, src/styles/FontStyles.ts, src/styles/GlobalStyles.ts
Adds default fonts to application.
=> [Feature] Add fonts

package.json, src/components/ApplicationLogo.tsx, src/pages/HomePage.tsx, src/styles/ColorVariables.ts, src/styles/GlobalStyles.ts
Adds application logo component
=> [Feature] Application logo

package.json, src/assets/arrow-left.svg, src/components/AsideCloseButton.tsx, src/components/LeftPanel.tsx, src/components/MainAside.tsx, src/custom.d.ts, src/pages/HomePage.tsx
Adds svg declaration, adds main aside panel, adds button for close aside.
=> [Feature] Main aside panel

package.json, public/index.html, public/manifest.json
Changes site description and application name in manifest
=> [Feature] Html description and app name

package.json, src/components/asides/AsideCloseButton.tsx, src/components/asides/AsideHeader.tsx, src/components/asides/MainAside.tsx, src/pages/HomePage.tsx
Adds header component for asides.
=> [Feature] Add header for asides

package.json, src/components/LanguageSwitch.tsx, src/components/asides/AsideHeader.tsx, src/styles/ColorVariables.ts
Adds LanguageSwitch component without logic for i18n.
=> [Feature] LanguageSwitch component

package.json, src/App.tsx, src/components/LanguageSwitch.tsx, src/contexts/LanguageContext.ts
Adds language context to application.
=> [Feature] Language context

package.json, src/components/MapView.tsx
=> [Feature] Change mapbox language

package.json, src/App.tsx, src/components/asides/MainAside.tsx, src/i18n/en/translation.json, src/i18n/index.ts, src/i18n/ru/translation.json, src/index.tsx, yarn.lock
=> [Feature] Implement i18n

package.json, src/App.tsx, src/i18n/index.ts, src/localStorage/LanguageController.ts
Adds controller for user language in local storage.
=> [Feature] Local storage controller for language

package.json, src/App.tsx, src/components/ApplicationLogo.tsx, src/components/LanguageSwitch.tsx, src/components/MapView.tsx, src/components/asides/AsideCloseButton.tsx, src/components/asides/AsideHeader.tsx, src/components/asides/MainAside.tsx, src/i18n/index.ts, src/localStorage/LanguageController.ts, src/pages/HomePage.tsx, src/styles/ShadowVariables.ts, yarn.lock
https://github.com/codex-team/eslint-config/pull/23
=> [Upgrade] CodeX eslint config

src/assets/burger-menu.svg, src/assets/search.svg, src/components/SearchLine.tsx, src/components/asides/AsideHeader.tsx, src/components/asides/MainAside.tsx, src/i18n/en/translation.json, src/i18n/ru/translation.json
Adds search line with menu button and search button.
=> [Feature] Search line

src/assets/double-arrows.svg, src/components/ApplicationLogo.tsx, src/components/LeftPanel.tsx, src/components/SearchLine.tsx, src/components/asides/AsideCloseButton.tsx, src/components/asides/AsideHeader.tsx, src/components/asides/MainAside.tsx, src/components/asides/MenuAside.tsx, src/contexts/MenuAsideContext.ts, src/interfaces/WithChildren.ts, src/interfaces/WithClassName.ts, src/styles/ShadowVariables.ts
Adds simple menu aside with context for opening and closing panel.
=> [Feature] Implements menu aside

package.json, src/components/Overlay.tsx, src/components/asides/MenuAside.tsx, src/styles/GlobalStyles.ts
Create overlay component for modals and asides.
=> [Feature] Overlay

package.json, src/assets/checkbox-checked.svg, src/assets/checkbox.svg, src/assets/cross.svg, src/components/CustomSelect.tsx, src/components/LanguageSwitch.tsx, src/components/SearchLine.tsx, src/components/asides/MainAside.tsx, src/i18n/en/translation.json, src/i18n/ru/translation.json, src/styles/ColorVariables.ts, src/styles/ShadowVariables.ts
=> [Feature] Custom select

src/components/CustomRange.tsx, src/components/CustomSelect.tsx, src/components/LeftPanel.tsx, src/components/YearsInputs.tsx, src/components/asides/MainAside.tsx
Added new component with two fields for years input.
Based on VUE [version](https://github.com/dh-center/st-retrospect-frontend/pull/74).
=> [Feature] Years inputs

src/assets/map.svg, src/components/AsideBottomButton.tsx, src/components/LeftPanel.tsx, src/components/asides/MainAside.tsx, src/i18n/en/translation.json, src/i18n/ru/translation.json, src/interfaces/WithOnClick.ts
Adds bottom buttons and routes logic for "Routes" and "Map search".
=> [Feature] Routes and search buttons

src/components/asides/AsideBottomButton.tsx, src/components/asides/AsideParametersWrapper.tsx, src/components/asides/MainAside.tsx
Adds block with box-shadow for asides.
=> [Feature] Add wrapper for aside parameters w/ box-shadow

src/components/CustomSelect.tsx, src/components/asides/AsideParametersWrapper.tsx, src/components/asides/MainAside.tsx, src/i18n/en/translation.json, src/i18n/ru/translation.json, src/styles/ColorVariables.ts, src/styles/GlobalStyles.ts
Adds routes header and parameters to aside.
=> [Feature] Routes aside parameters

.env, package.json, relay.config.js, schema.graphql, src/App.tsx, src/RelayEnvironment.ts, src/babel.d.ts, src/components/RouteCard.tsx, src/components/RoutesList.tsx, src/components/__generated__/RouteCard_quest.graphql.ts, src/components/__generated__/RoutesListPaginationQuery.graphql.ts, src/components/__generated__/RoutesListQuery.graphql.ts, src/components/__generated__/RoutesList_questsConnection.graphql.ts, src/components/asides/AsideBottomButton.tsx, src/components/asides/MainAside.tsx, src/contexts/RelayEnvironmentContext.tsx, src/i18n/en/translation.json, src/i18n/ru/translation.json, src/styles/ColorVariables.ts, src/styles/GlobalStyles.ts, yarn.lock
Adds routes list with pagination.
=> [Feature] Routes list

src/assets/arrow-left-second.svg, src/components/CustomSelect.tsx, src/components/LeftPanel.tsx, src/components/RouteCard.tsx, src/components/RouteItem.tsx, src/components/RoutesList.tsx, src/components/__generated__/RouteCardQuery.graphql.ts, src/components/__generated__/RouteItem_quest.graphql.ts, src/components/__generated__/RoutesListPaginationQuery.graphql.ts, src/components/__generated__/RoutesListQuery.graphql.ts, src/components/__generated__/RoutesList_questsConnection.graphql.ts, src/components/asides/MainAside.tsx, src/i18n/en/translation.json, src/i18n/ru/translation.json, src/styles/GlobalStyles.ts
Adds route card with information.
=> [Feature] Route card

src/components/RouteItem.tsx
Adds hover behavior for route items.
=> [Feature] Hover on route item

src/assets/arrow-left-second.svg, src/assets/arrow-left.svg, src/assets/burger-menu.svg, src/assets/checkbox-checked.svg, src/components/Menu.tsx
Recolors svg icons to blue, adds hover behavior for menu items.
=> [Feature] Recolor svg icons, hover for menu items

src/components/asides/MainAside.tsx
Uses Loader component in suspenses.
=> [Feature] Using loader in suspenses

.github/workflows/main.yml, package.json, src/assets/arrow-left-second.svg, src/assets/map-pin.svg, src/components/Menu.tsx, src/components/RouteBlocks/LocationInstanceBlock.tsx, src/components/RouteBlocks/__generated__/LocationInstanceBlockQuery.graphql.ts, src/components/RouteCard.tsx, src/components/RoutePassingRenderer.tsx, src/components/RouteStageCard.tsx, src/components/__generated__/RoutePassingRendererQuery.graphql.ts, src/components/asides/MainAside.tsx, src/contexts/RelayEnvironmentContext.tsx, src/custom.d.ts, src/i18n/en/translation.json, src/i18n/ru/translation.json, src/interfaces/QuestBlocks.ts
=> [Feature] Route passing

src/components/LocationInstanceItem.tsx, src/components/LocationInstancesList.tsx, src/components/RouteItem.tsx, src/components/RoutesList.tsx, src/components/asides/MainAside.tsx, src/components/lists/Delimiter.ts, src/components/lists/Image.ts, src/components/lists/InformationWrapper.ts, src/components/lists/Item.ts, src/components/lists/ListWrapper.ts, src/components/lists/SecondaryInformation.ts, src/components/lists/index.ts
Add list and item for location instance. Move same components to `src/components/lists` folder.
=> [Feature] Add location instance item component

src/assets/person-no-photo.svg, src/components/LocationInstanceCard.tsx, src/components/LocationInstanceItem.tsx, src/components/RelatedPersonBlock.tsx, src/components/RouteCard.tsx, src/components/__generated__/LocationInstanceCardQuery.graphql.ts, src/components/__generated__/RelatedPersonBlock_person.graphql.ts, src/components/asides/MainAside.tsx, src/components/cards/CardWrapper.ts, src/components/cards/Description.ts, src/components/cards/GoingBackButton.tsx, src/components/cards/Image.ts, src/components/cards/InformationWrapper.ts, src/components/cards/Name.ts, src/components/cards/index.ts, src/i18n/en/translation.json, src/i18n/ru/translation.json, src/lib/abbreviatePersonName.ts, src/lib/abbreviatedPersonName.ts
Add location instance card with information about it.
=> [Feature] Location instance card

src/components/YearsInputs.tsx, src/styles/ColorVariables.ts
If years inputs are out of range, then they're with light red background and red border.
=> [Feature] Add styles for :out-of-range pseudo

schema.graphql, src/components/LocationInstanceItem.tsx, src/components/LocationInstancesList.tsx, src/components/SearchForm.tsx, src/components/__generated__/LocationInstanceItem_locationInstance.graphql.ts, src/components/__generated__/LocationInstancesListQuery.graphql.ts, src/components/asides/MainAside.tsx, src/lib/useQuery.ts
=> [Feature] Implement search api

package.json, src/components/mapContent/LocationInstanceRelationsPopup.tsx, src/components/mapContent/RelationCard.tsx
=> [Feature] Add delimiter to popup without relations

package.json, src/components/RelatedPersonBlock.tsx
=> [Fix] Outline when open popup

package.json, schema.graphql, src/App.tsx, src/components/LocationInstancesList.tsx, src/components/PersonItem.tsx, src/components/SearchResultList.tsx, src/components/__generated__/LocationInstancesListQuery.graphql.ts, src/components/__generated__/PersonItem_person.graphql.ts, src/components/__generated__/SearchResultListQuery.graphql.ts, src/components/asides/MainAside.tsx, src/lib/uniqueObjectsByIds.ts, src/styles/BorderVariables.ts
Displays persons and locations in results.
=> [Feature] Use relation search

package.json, src/components/SearchForm.tsx, src/components/asides/MainAside.tsx, src/components/customSelects/CustomSelect.tsx, src/components/customSelects/TagsCustomSelect.tsx
=> [Fix] Displays parameters from query in search form

package.json, src/components/LocationInstanceCard.tsx, src/components/cards/InformationWithTitle.ts, src/components/mapContent/Marker.tsx
Now marker changes position when lnglat prop will change.
=> [Fix] Marker displaying

package.json, src/components/SearchForm.tsx
=> [Fix] Redirect to '/' pathname on search

package.json, src/components/LeftPanel.tsx, src/components/SearchForm.tsx, src/components/asides/MenuAside.tsx, src/components/customSelects/CustomSelect.tsx, src/lib/useOnClickOutside.ts, yarn.lock
- Add onClickOutside hook
- Fix bug with empty select
- Upgrade dependencies
=> [Feature] Outside click hook

package.json, schema.graphql, src/components/SearchResultList.tsx, src/components/__generated__/SearchResultListQuery.graphql.ts
=> [Feature] New search api
